In [ ]:
#Why do we need to find data?  
#The simplest way to find data
#lists 
#passwordGenenerator

In [3]:
import numpy as np

array = np.arange(0, 11) 

print(array)  


[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
array[1]

1

In [5]:
new=array[1]+array[2]

In [7]:
print(new)

3


In [8]:
newArray=array+array

In [9]:
print(newArray)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [10]:
multArr=array*array

In [11]:
print(multArr)

[  0   1   4   9  16  25  36  49  64  81 100]


In [13]:
np.append()

IndexError: index 1000 is out of bounds for axis 0 with size 11

In [ ]:
import numpy as np

# Existing array
original_array = np.array([1, 2, 3, 4, 5])

# Element to append
new_element = 6

# Append the new element to the original array
new_array = np.append(original_array, new_element)

print(new_array)  # Output the updated array
